config/routes.rb
Rails.application.routes.draw do
  root 'laws#index'
  resources :laws 
  get 'criminaldefense', to: 'laws#criminaldefense'
  get 'injury', to: 'laws#injury'
  get 'civilright', to: 'laws#civilright'
  get 'spanish', to: 'laws#spanish'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/criminals_controller.rb
class CriminalsController < ApplicationController
    def show
    end
end

app/controllers/laws_controller.rb
class LawsController < ApplicationController
    def index
    end

    def new
    end
    
    def show
    end

    def criminaldefense
    end

    def injury
    end

    def civilright
    end

    def spanish
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/criminals_helper.rb
module CriminalsHelper
end

app/helpers/laws_helper.rb
module LawsHelper
end

app/views/laws/civilright.html.erb
<br />
<br />
<div class="col-10 offset-1">

<h1><u>Civil Rights</u></h1>
<p> What are Civil Rights here in the United States?</p>
<p>Civil rights is the promise of equivalent social opportunities and protection under law, regardless race, religion, or other personal characters.</p>
<br />
<h1><u>Discrimination</u></h1>
<p>If you feel like you have been discriminated due to the following:</p>
<p>Race/Color</p>
<p>Age</p>
<p>Sex</p>
<p>Religion</p>
<p>Sexual Harrasement</p>
<p>Pregnancy</p>
<p>National Origin </p>
<p> Or any other trait that you may believe has violated your Civil Rights</p>
<br />
<h1><u>Excessive Force</u></h1>
<p>Excessive Force is the force in excess an officer of any law enforcement agency may have used due to this person or group believed it was necessary.</p>
<p>The officers of law enforcement agencies can be liable for using excessive force in arrests, seizures, and investigatory stops. Officers of these law enforcement agencies can also be liable if he or she does not prevent another officer from effecting excessive force.</p>
<p>Whether this person, or group believes that can be disputable in a court of law, and can be determined by a jury. </p>
<br />
<h1><u>Cruel and Unusual Punishment</u></h1>
<p> In the constitution of the United States of America, amendment number 8 states “excessive bail shall not be required, nor excessive fines imposed, nor cruel and unusual punishments inflicted".</p>
<p>In simpler terms, it means that courts are required to give you a fair bail, fine, and not a cruel & unusual sentence. </p>
<h1><b> Contact Me to set up an appointment to talk about your situation.</b></h1>
</div>

app/views/laws/criminaldefense.html.erb
<div class="col-10 offset-1">
<br />
  <h1><u>Criminal Defense Page</u></h1>
  <p>Criminal defense is the act of defending a person, or company of crimes they have been accused of committing. </p>
  <br />

<h1><u>Juvenile Crimes</u></h1>
<p>This is when the law of the United States has been violated by a person who has not reached the age of 18.</p>

<h1><u>State Crimes</u></h1>
<p>State crimes are actions that violate the state’s law. These include:</p>
<p>-Robbery </p>
<p>-Burglary & Theft</p>
<p>-Arson</p>
<p>-Homicide</p>
<p>-Rape</p>

<h1><u>Federal Crimes</u></h1>
<p>Federal Crimes are crimes that violate the USA federal code, or the individual carries criminal activity over several states. These include:</p>
<p>-Commercial Fraud </p>
<p>-Wire Fraud</p>
<p>-Drug Trafficking</p>
<p>-Several other crimes can become Federal Crimes, subject to condition. </p>

<h1><b> Contact Me to set up an appointment to talk about your situation.</b></h1>


</div>

app/views/laws/index.html.erb
<div class="col-10 offset-1">

<div class="photo col-12 col-sm-4">
  <%= image_tag 'david_cantu.jpg', class: 'img-fluid' %>
</div>
<p class="motto">The aim is to protect, preserve, and improve the constitution, our legal system and the people of our community.</p>


<h1 class"title"><u>Background</u></h1>
<br />
<p class="background">David Cantu is originally from McAllen, Texas, where he attended James “Nikki” Row High School. Upon graduating he enrolled into St. Mary’s University in San Antonio, where he received a Baccalaureate degree of Business Administration in Accounting. Mr. Cantu then followed his dream and enrolled at Texas Southern University’s Thurgood Marshall School of Law in Houston, Texas.  </p>
<p class="background">Upon graduating and becoming a licensed attorney with the State Bar of Texas, David transitioned back to McAllen and began practicing law with his father, a very respected lawyer, Arturo R. Cantu. David focused on representing the indigent in criminal cases, ranging from misdemeanors against the State of Texas to Federal crimes against the United States of America.  </p>
<p class="background">In December 2019, David accepted an offer for the Hidalgo County District Attorney’s Office in the Civil Litigation Division, in which he could focus on government law including contracts and employment law.  </p>
<p class="background">Mr. Cantu continues to take cases, and is open to consult on legal matters if need be. This website provides you several methods to contact Mr. Cantu.</p>
</div>

app/views/laws/injury.html.erb
<br/>
<br />
<div class="col-10 offset-1">

<h1><u>Injury</u></h1>
<br />

<p><u>Auto Collision Injury</u></p>
<p>David Cantu can help you if you have been involved in an automobile accident. It is important to seek help after an accident after contacting the police due to injury, damage to your vehicle, liability, medical attention if necessary. Mr. Cantu has experience with many cases he has helped in his career, and can guide you in the correct path. </p>


<p><u>Trucking Accidents Injury</u></p>

<p>Trucking Accidents are when an 18-wheeler, semi-trucks, or any other commercial vehicle causes personal injury and or property damage. It is important to contact Mr. Cantu if you have been involved in an accident with one of these vehicles. He can help you take a look a special truckers licenses, compensation for injury, and negligence on part of the driver and or company. </p>

<p><u>Premises Liability </u></p>
<p>Any location you visit, either for shopping or leisure is expected to be safe for the visitors. Premises liability is a set of required rules of the Texan property owner which ensure the safety of the visitors. These include dog bites, slips and falls, amusement park accidents, swimming pool accidents, and several more.  David Cantu has had experience with these cases, and can help you with your situation.</p>
<br />

<h1><b>Contact Me to set up an appointment to talk about your situation.</b></h1>
</div>

app/views/laws/spanish.html.erb
<br />
<div class="col-10 offset-1">

<h1> Español</h1>

<p>David Cantu es originario del Valle del Rio Grande, y sabe lo importante que es atender a sus cliente en español. Aunque el Sr. Cantu no domina el español, el tiene varios recursos para poder ayudarte en tu caso. </p>

<p>David Cantu tiene experiencia en el area de crimenes juveniles, estatales, y federales. David Cantu tambien tiene experiencia en derechos civiles y algun tipo de lesion.</p>

<p>Cualquier pregunta que tenga sobre un asunto legal no dude en contactar. </p>




</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Davidcantu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/ebb4fbda58.js" crossorigin="anonymous"></script>
     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
  <div id="flex-content-container">
  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'David R. Cantu', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
    <p class="navbar-subbrand">Attorney at Law</p>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <%= link_to 'Home', root_path, class: 'nav-link' %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Civil Rights
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Discrimination', civilright_path, class: 'dropdown-item' %>
          <%= link_to 'Excessive Force', civilright_path, class: 'dropdown-item' %>
          <%= link_to 'Cruel and Unusual Punishment', civilright_path, class: 'dropdown-item' %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Crimial Defense
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Juvenile Crimes', criminaldefense_path, class: 'dropdown-item' %>
          <%= link_to 'State Crimes', criminaldefense_path, class: 'dropdown-item' %>
          <%= link_to 'Federal Crimes', criminaldefense_path, class: 'dropdown-item' %>

      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Injury
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to 'Auto Collisions', injury_path, class: 'dropdown-item' %>
        <%= link_to 'Truck Accidents', injury_path, class: 'dropdown-item' %>
        <%= link_to 'Premises Liability(slip and falls)', injury_path, class: 'dropdown-item' %>
        </div>

      </li>
      <%= link_to 'Español', spanish_path, class: 'nav-link' %>

    </ul>

  </div>
  <a class="contactnavbar" href="tel:9569849245">956-984-9245</a>



</nav>
    <%= yield %>
    </div>
    <div id="footer">
    <div class="container">
    <div class="row">
    <div class="col-12 col-sm-3">
    <%= link_to 'Home', root_path %>
    <br />
      <%= link_to 'Civil Rights', civilright_path %>
      <br />
      <%= link_to 'Criminal Defense', criminaldefense_path %>
      <br />
      <%= link_to 'Injury', injury_path %>
      <br />
      <%= link_to 'Español', spanish_path %>
    </div>
    <div class="col-12 col-sm-3">
      <b><u>About</u></b>
      <br />
      <a href="
      https://legalethicstexas.com/Downloads/Texas-Lawyers-Creed/Texas_Lawyers_Creed.aspx
      " target="_blank">Texas Lawyers Creed</a>
      <br />
      <a href="https://www.texasbar.com/AM/Template.cfm?Section=Ethics_Resources&Template=/CM/ContentDisplay.cfm&ContentID=30311" target="_blank">A Mandate for Professionalism</a>
      <br />

      </div>
    <div class="col-12 col-sm-3">
      <b><u>Contact</u></b>
      <br />
      <a href="mailto:davidr@cantulawfirm.net"target=_top>davidr@cantulawfirm.net</a>
      <br />
      <a href="tel:9569849245">956-984-9245</a>
      <u></u>
      <br />
      McAllen, Texas 78501
    </div>
    <div class="col-12 col-sm-3">
      <b><u>Social</u></b>
      <br />
      <%= link_to 'http://linkedin.com/in/david-r-cantu-91363861' do %>
      <span class="fa fa-linkedin-square fa-2x social-button"></span>
      <% end %>
      <%= link_to href="mailto:davidr@cantulawfirm.net" do %>
      <span class="far fa-envelope fa-2x social-button"></span>
      <% end %>
      <%= link_to href="tel:9569849245" do %>
      <span class="fas fa-phone fa-2x social-button"></span>
      <% end %>
      
    </div>
  </div>      
  <br />
    </div>
  </div>
  </body>
</html>